name: eams
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+2
  flutter_plugin_android_lifecycle: ^2.0.8
  geolocator: ^9.0.2
  path_provider: ^2.0.15
  path: ^1.8.3
  intl: ^0.18.0
  table_calendar: ^3.0.9
  fl_chart: ^0.55.0
  google_mlkit_face_detection: ^0.5.0
  flutter_local_notifications: ^13.0.0
  workmanager: ^0.5.0
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
